# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:1.3.3
        environment:
          AWS_REGION: eu-west-1
          AWS_DEFAULT_REGION: eu-west-1
          AWS_AMI_REGIONS: "ap-northeast-1,ap-northeast-2,ap-south-1,ap-southeast-1,ap-southeast-2,ca-central-1,eu-central-1,eu-north-1,eu-west-1,eu-west-2,eu-west-3,sa-east-1,us-east-1,us-east-2,us-west-1,us-west-2"
          AWS_SSH_USERNAME: ubuntu
          AWS_SOURCE_AMI: ami-0233bae36f499afe8
          AWS_INTANCE_TYPE: c4.large
          AWS_SPOT_PRICE: 0.03
          KUBERNETES_VERSION: 1.12.4
          ETCD_RELEASE_TAG: 3.1.11
          K8S_DNS_RELEASE_TAG: 1.14.8
          HELM_RELEASE_TAG: v2.12.1
          VAULT_VERSION: 0.11.6
          BASE_NAME: pipeline-cp-image
    steps:
      - checkout

      - run:
          name: Build Packer
          no_output_timeout: 2700
          command: |
            GIT_REV=$(git rev-parse --short HEAD)
            GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            export AWS_IMAGE_NAME=$BASE_NAME-$GIT_BRANCH-$GIT_REV-$(date +%y%m%d%H%M)
            packer build ./packer.json